enum Error {
    NO_ERROR = 0,
    INVALID_USER = 1,
    USER_LAB_HIDDEN = 2,
    NO_GROWING_CREATURES = 3,
    CREATURE_DOES_NOT_EXIST = 4,
    INVALID_API_CALL = 5,
    SPECIES_DOES_NOT_EXIST = 6,
    TAB_DOES_NOT_EXIST = 7,
    TAB_HIDDEN = 8,
}
